name: Build app bundle

on: 
  push:
    branches: [ "main" ]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup flutter sdk
        uses: flutter-actions/setup-flutter@v3
        with: 
          channel: stable
          version: 3.24.1

      - name: install dependencies
        run: flutter pub get

      # - name: analyze source code
      #   run: flutter analyze

      # - name: build bundle
      #   run: flutter build appbundle --release

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.1'
          release_name: 'App version 1.0.1'
          body: 'something here'
          draft: false
          prerelease: false

      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_ACTION: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/bundle/release/app-release.aab
          asset_name: vma-release.aab
          asset_content_type: application/vnd.android.package-archive
